### ISSUE TITLE
Provide the response in exceptions when applicable

### ISSUE THREAD

**Issue by greg0ire** [nexylan/paybox-direct#30]
If would be nice to be able to see the response object when an exception is displayed. Not sure if it should be part of the message or rather be a property of the exception, and have this property be nicely displayed by some framework integration class.

When logging the exception, this property should be added to the `$context` argument.

**Comment by soullivaneuh** [comment]
> Not sure if it should be part of the message or rather be a property

The message is already constructed from the response.
See: https://github.com/nexylan/paybox-direct/blob/1190966f9f37915cae4d7b6a8366eae2bd5eed08/src/HttpClient/AbstractHttpClient.php#L100

I think it should be as a property in addition to the message.

> and have this property be nicely displayed by some framework integration class.

What do you mean?

> When logging the exception, this property should be added to the `$context` argument.

I'm not sure of what you are talking about. From where `$context` come from?

**Comment by greg0ire** [comment]
> What do you mean?

Well if it is not part of the exception message, you can't expect the framework to display it, do you?

`$context` is the second argument of `Psr\LoggerInterface::log()`. Some keys, like `exception` trigger special mechanisms (in Sentry for instance, it will be nicely displayed)

**Comment by soullivaneuh** [comment]
> Well if it is not part of the exception message, you can't expect the framework to display it, do you?

Well, I don't think so. But what do you mean by "have this property be nicely displayed"? What do you want except have a... property? :smile: 

> `$context` is the second argument of `Psr\LoggerInterface::log()`. Some keys, like `exception` trigger special mechanisms (in Sentry for instance, it will be nicely displayed)

Oh ok it's for loggin. Will open another issue for that.

**Comment by greg0ire** [comment]
> What do you want except have a... property? :smile:

Nothing more, really, but… is it even displayed by default? As far as I know, framework will display the message… not so sure about extra properties…

**Comment by soullivaneuh** [comment]
> Nothing more, really, but… is it even displayed by default? As far as I know, framework will display the message… not so sure about extra properties…

Well, I would like to add the response object on the exception to permit developer to manipulate it if needed after all.

**Comment by greg0ire** [comment]
> Well, I would like to add the response object on the exception to permit developer to manipulate it if needed after all.

Yeah so it becomes the responsability of the developer, not of the framework, which is what makes me feel this isn't great.

**Comment by soullivaneuh** [comment]
> Yeah so it becomes the responsability of the developer, not of the framework, which is what makes me feel this isn't great.

Why it isn't great for you? For example the developer would like to get the response from the exception to send details by email or whatever...

**Comment by greg0ire** [comment]
It's great to get the response from the exception, but I think it should also be in the exception message, because that way the developer does not have anything to do to see it when developing.

**Comment by soullivaneuh** [comment]
> but I think it should also be in the exception message

I never talked about removing the exception message. :wink:

**Comment by greg0ire** [comment]
Right. My bad.
