### ISSUE TITLE
Review php version

### ISSUE THREAD

**Issue by mnwalker** [nexylan/paybox-direct#67]
The readme states 5.6 but composer says 7.4

Is 7.4 really needed or would it work fine on any 7.x?

Would expect backwards compatability to be possible with the right combination of dependency versions.
Or if not would you be open to me building a branch with full 7.x support?

**Comment by soullivaneuh** [comment]
Hi @mnwalker,

The 5.6 requirement on the readme was a mistake. Please see https://github.com/nexylan/paybox-direct/pull/68.

We won't support any lower PHP version than 7.4. By the way, the next big cleanup would drop support of PHP 7.

Thanks for the report!

**Comment by mnwalker** [comment]
Whats the reasoning behind dropping php 7 support? 
PHP 8 is only a few months old, lot of systems won't be able to upgrade that fast.

**Comment by soullivaneuh** [comment]
Simple: We can not allow more resources to maintain multiple PHP version compatibilities and going to the latest is always the way to go (for PHP or anything else).

**Comment by mnwalker** [comment]
I opened this topic by offering the resources to support additional versions.....
But seems I will just look to fork instead. Thanks for update.

**Comment by soullivaneuh** [comment]
@mnwalker And I thank you for that! :+1: 

However, this is not only a resource problematic. Maintaining old version means increasing the code base complexity and this is not something we want to bring on our projects.
